import Head from 'next/head'
import { Inter } from 'next/font/google'
import ProductList from './products/ProductList'
import Header from '@/component/appBar/Header'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Nature care.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ProductList />
    </>
  )
}
